### ISSUE TITLE
Wrong rotation distance in a sample config

### ISSUE THREAD

**Issue by josef-jelinek** [3DPrintingMods/VoronTrident-BeltedZ#15]
The economy planetary gearboxes linked have true ratio of 57:11, which is rounded in descriptions to 5.18:1 (or sometimes even 5:1).
That means that for 20T 2GT, the real rotation distance is 40*11/57 which is about 7.7193.
The configuration shows 7.75, which would mean that the gear ratio is close to 5.16129:1.
It seems like this disparity should be subtracting about 0.03mm each rotation resulting in close to 1mm subtracted from 250mm maximum print height.

After I wrote above, I found out that this exact case is described in klipper docs and can be set precisely using gear_ratio to the one above: https://www.klipper3d.org/Rotation_Distance.html#using-a-gear_ratio

**Comment by ghost** [comment]
Thanks for pointing this out.  I've updated the example config with new rotation distance and gear ratio.
