### ISSUE TITLE
Z Motor Skirts L&R for 350?

### ISSUE THREAD

**Issue by Killajoedotcom** [3DPrintingMods/VoronTrident-BeltedZ#5]
Is there a chance you could make the Z motor skirt mounts for a 350 sized Trident? I'm thinking the current set only fit a 250.

**Comment by thiagolocatelli** [comment]
@tdlane1 what would we need to do to get the motor mounts for 350? Just extend them?

**Comment by Killajoedotcom** [comment]
> @tdlane1 what would we need to do to get the motor mounts for 350? Just extend them?

Yes, I believe so. The 350 skirt github link here for reference:
[https://github.com/VoronDesign/Voron-Trident/tree/main/STLs/Skirt/350](url)

**Comment by ghost** [comment]
I can work on this.  The current design used the 300mm front skirts as a base model for the motor skirts.  250 compatibility is provided by the modified midskirts in the CAD.  Extension of the existing motor skirts to 350mm size should be all that's needed.

**Comment by Killajoedotcom** [comment]
That's great! Thanks so much. Keen to get this installed because I'm rebuilding the Trident anyway.

**Comment by thiagolocatelli** [comment]
@Killajoedotcom @tdlane1 has just added the skirts. Tweet some pictures once you rebuild the Trident.

**Comment by Killajoedotcom** [comment]
> @Killajoedotcom @tdlane1 has just added the skirts. Tweet some pictures once you rebuild the Trident.

Will do! I'll tag you both!
